language: python
python:
   "3.6.1"
install:
    "pip install -r requirements.txt"
script:
    - "nose2 test_users"
    - "nose2 test_categories.py"
    - "nose2 test_categories  "
    - "coverage run test_users.py"
    - "coverage run test_categories.py"
    - "coverage run test_recipes.py"
after_success: coveralls

